on:
  push:
    branches:
      - main
  pull_request:

name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Load build cache
        uses: Swatinem/rust-cache@v2
      - name: Set github problem matcher for rust
        uses: r7kamura/rust-problem-matchers@v1
      - name: Format check
        run: cargo fmt --check
      - name: Check docs
        run: cargo doc --no-deps --document-private-items --all-features
      - name: Lint with all features and compile targets
        run: cargo clippy --all-features --all-targets --no-deps -- --deny warnings
      - name: Test with all features and compile targets
        run: cargo test --all-features --all-targets
      - name: Run Cargo deny
        uses: EmbarkStudios/cargo-deny-action@v1

      # Cancel the whole workflow if any step fails.
      - name: Cancel this workflow
        if: failure()
        uses: andymckay/cancel-action@0.3
